#Taller de operadores
nombre = input("Dame tu nombre : ")
print("OK!,", nombre, "Vamos a realizar unas operaciones" )
#----------------SUMA-------------
print("Vamos a comenzar con suma")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de sumar tus numeros es :", a+b)
#-----------------RESTA----------------
print("Ahora vamos a restar")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de restar tus numeros es :", a-b)
#-----------------MULTIPLICACION------------------
print("Ahora con multiplicacion")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de multiplicar tus numeros es :", a*b)
#------------------DIVICION-------------------------
print("Ahora vamos a dividir")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de dividir tus numeros es :", a/b)
#----------------DIVISION ENTERA------------
print("Seguimos con division entera")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de la division entera de tus numeros es :", a//b)
#------------------DIVISION DE MUDULO----------------------
print("Ahora vamos con la division de modulo")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El residuo de tu division es :", a%b)
#-------------------POTENCIA----------------------
print("Ahora vamos con la poetencia")
print(nombre, "Dame tu primer numero")
a = int(input())
print(nombre, "Dame tu segundo numero")
b = int(input())
print(f"El resultado de potenciar tus numeros es :", a**b)